name: Prefix main commits

on:
  push:
    branches:
      - main

jobs:
  prefix-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ORG_PAT }}

      - name: Set up Git    
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Amend commit message with [update main]
        run: |
            COMMIT_MSG="[update main] => $(git log -1 --pretty=%B)"
            git commit --amend -m "$NEW_COMMIT_MSG"
            git push --force-with-lease origin main