name: Prefix main commits

on:
  push:
    branches:
      - main

jobs:
  prefix-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last commit message
        id: last_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "message=$COMMIT_MSG" >> $GITHUB_ENV

      - name: Amend commit message with [update main] (check if prefix is missing)
        if: startsWith(env.message, '[update main]') == false
        run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions - Update Main"

            NEW_COMMIT_MSG="[update main] => ${{ env.message }}"
            git commit --amend -m "$NEW_COMMIT_MSG"
            git push --force-with-lease origin main