name: Prefix main commits

on:
  push:
    branches:
      - main

jobs:
  prefix-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last commit message
        id: last_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "message=$COMMIT_MSG" >> $GITHUB_ENV

      - name: Amend commit message with [update main] (check if prefix is missing)
        if: startsWith(env.message, '[update main]') == false
        run: |
            AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
            AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')

            git config user.name "$AUTHOR_NAME"
            git config user.email "$AUTHOR_EMAIL"

            NEW_COMMIT_MSG="[update main] => ${{ env.message }}"
            git commit "$NEW_COMMIT_MSG"
            git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}